server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java5MSAuthDb
    password: ${PG_ADMIN_PASSWORD}
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secretKey: ${SECRETKEY}
  issuer: ${ISSUER}
  audience: ${AUDIENCE}